### PR TITLE
Fix overstripping of replacement character

### LINKED ISSUE #21: File name with ! (Exclamation mark only) return blank
**Version:** 4.2.0
**Actual:**   If any file contains only the !!!!!.docx name then the filenamify return .docx only the extension file name gets blank.
**Expected:**  As exclamation (!) mark is the valid filename character this should return the same name.

### PR DESCRIPTION
**Pull request by tomasklaen**
Fixes #21.

### CODE REVIEW

**Comment by sindresorhus** [comment]
CI is failing

**Comment by tomasklaen** [comment]
Sorry. I've only run ava on my end, pressed push and went to sleep :)

**Comment by sindresorhus** [comment]
Thanks ;)

Do you plan more changes or should I do a release now?

**Comment by tomasklaen** [comment]
No this was the last one. Release away.

**Pull request merged**
